title: 🚔 policiaDigital
description: "Car Patrol Survival - Esquiva obstáculos al ritmo"
baseurl: /policiadigital
url: https://mxjworld.github.io

theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Configuración
markdown: kramdown
lang: es
author: mxjworld
repository: mxjworld/policiadigital

# Headers
include:
  - .nojekyll
  - service-worker.js
  - manifest.json

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
